<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iFrameRoute</name>
   <tag></tag>
   <elementGuidId>0c8ccd87-e851-4a0f-8c12-0c61b64351df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeRoute']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframeRoute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/IFrames/iFrameRoutes</value>
      <webElementGuid>66831c80-c3f5-4ebb-8605-ac6b3a8446e6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
