<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchDoc_TextBox</name>
   <tag></tag>
   <elementGuidId>5e4fcd6a-e1be-4cc7-a890-2b3ab4a0aca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@type='search']</value>
      <webElementGuid>65d83508-0d76-4316-8b35-52b73658dbaf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
