<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Logout_Detailview</name>
   <tag></tag>
   <elementGuidId>288afc97-1ddf-4403-9f53-0658ca5b19a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Detailview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='Detailview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ab7725e7-8f3d-42bd-ba59-c8dadebaa5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Detailview</value>
      <webElementGuid>690d53a1-de02-42de-93a0-1dba0c909559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Detailview</value>
      <webElementGuid>cca89cc4-f6c2-4c9e-a381-abf548e40b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>hideModuleList()</value>
      <webElementGuid>108667d4-ea3d-4839-afbd-1d2585b49d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onFrameLoad(this)</value>
      <webElementGuid>af1d1229-8ce8-4cf0-9e46-9a82580b49b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-wrapper</value>
      <webElementGuid>de3379b0-f000-4c5e-9283-b391f58eb878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Detailview&quot;)</value>
      <webElementGuid>dba4bff9-b024-460b-bffb-acc2260766b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='Detailview']</value>
      <webElementGuid>f4ae4f01-2c06-4512-a799-6011bac8531e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/main/iframe</value>
      <webElementGuid>290d08d2-2b99-467c-8b58-4cd1adb7b8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>196b9678-fb9c-47a6-b879-44792185ea21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'Detailview' and @id = 'Detailview']</value>
      <webElementGuid>5785bf61-12a9-44dc-9e6f-5c929cbf59e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
