<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_QA-Project-01_iframeActions_top</name>
   <tag></tag>
   <elementGuidId>c16c0fad-b791-45e5-92b3-b880eb72fd86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframeTree</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeTree']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5aedfee9-c098-40f3-b5da-8fbcfafd607a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeTree</value>
      <webElementGuid>03e52b0d-adb6-4f41-89cd-3350b4ad6043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframeActions_top</value>
      <webElementGuid>c1adbbfb-8a8b-416f-a17b-6d963a5f1748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>98905533-e705-42f3-98b3-a3ec56c3fb2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>hidelaodingsymbol()</value>
      <webElementGuid>a0314b29-7af3-4300-85e0-c2a195dfe576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cloudqa4.ewqims.com///Common/DocPro/levelformsuite/levelformsuiteView?isNew=1&amp;suite=0&amp;righttype=2&amp;sitelevelname=Root Level&amp;parentlevelid=0&amp;levelid=#</value>
      <webElementGuid>2aaed5e5-a5fe-4126-a0c6-083d020d84e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeTree&quot;)</value>
      <webElementGuid>a46a0804-d130-41e0-b943-12c121138b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DocPro_Module/Levels_Page/Page_EwQIMS/iframe_Logout_Detailview</value>
      <webElementGuid>a13c375d-d06d-4cf7-99e3-301a95538f0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeTree']</value>
      <webElementGuid>cbc86dc4-f0c6-494f-a1d9-631ce92d0f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentPanel']/div/iframe</value>
      <webElementGuid>ff3e43f0-c7ef-4d5c-b218-d62b4819cc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>85394e37-fd0c-49ab-bc5f-2d764d1c7b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeTree' and @name = 'iframeActions_top' and @src = 'https://cloudqa4.ewqims.com///Common/DocPro/levelformsuite/levelformsuiteView?isNew=1&amp;suite=0&amp;righttype=2&amp;sitelevelname=Root Level&amp;parentlevelid=0&amp;levelid=#']</value>
      <webElementGuid>a51ff76e-a983-467a-afd4-112f1822da9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
