<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Allow Site Sub-levels Creation</name>
   <tag></tag>
   <elementGuidId>8abe251c-7d3c-4913-8afb-53a0cecce818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thAllowSiteSub</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='thAllowSiteSub']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>125bd680-67e0-4f65-98d7-3df560b7bbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thAllowSiteSub</value>
      <webElementGuid>2637bb12-db6e-436c-98f6-d01c325ff3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chkAllowSiteSub</value>
      <webElementGuid>dc63aca5-4528-46da-ba13-1d18536a6d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label</value>
      <webElementGuid>ce3977b8-ef7f-45f9-81e4-a88e859840a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allow Site Sub-levels Creation?</value>
      <webElementGuid>7a2dd1e2-ba11-4823-a2cc-c6e9cec1371d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thAllowSiteSub&quot;)</value>
      <webElementGuid>ee0ba7d6-61f9-4fdd-bebe-26be15ede995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DocPro_Module/Levels_Page/Page_EwQIMS/iframe_QA-Project-01_iframeActions_top</value>
      <webElementGuid>957a6904-ee4f-4461-8250-9ced7637daa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='thAllowSiteSub']</value>
      <webElementGuid>2702a679-fa84-4bf4-a2e1-0943929fea97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmlevelformsite']/div/div[4]/div[2]/div/div/label</value>
      <webElementGuid>afa309f8-d4d6-4ba6-b1ae-5bc6d127d0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow Site Modification'])[1]/following::label[1]</value>
      <webElementGuid>e1ea854b-e7ac-42ea-945c-414801715504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[4]/following::label[2]</value>
      <webElementGuid>a64c264f-56ca-4dab-a72f-304e0283ad03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::label[1]</value>
      <webElementGuid>b1437964-bd3d-414e-abcb-2d3710371eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::label[1]</value>
      <webElementGuid>36a33d74-bce1-4358-8dd7-0553219236f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Allow Site Sub-levels Creation?']/parent::*</value>
      <webElementGuid>8b69aa19-1206-4af9-ba26-934de063b810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/label</value>
      <webElementGuid>6ec1db8f-be93-458c-b1d8-bbd2ea92cbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'thAllowSiteSub' and (text() = 'Allow Site Sub-levels Creation?' or . = 'Allow Site Sub-levels Creation?')]</value>
      <webElementGuid>f137500d-9c5b-4dab-adf3-772ed255e99d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
