<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Rights scenario</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>908fda47-c014-4837-97bb-47a9efc7377f</testSuiteGuid>
   <testCaseLink>
      <guid>2c185538-4646-487f-8091-8b44a3990040</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Rights Scenario/01.Sub Level Access/TC 23748_49_60 Validate Full Site Access</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d78cd134-6813-4ad0-afd2-13413981c5dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ec1548e-0009-4c15-9d34-f30c8a248462</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b155d8d-8853-4c73-b309-a78423dd7e90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Rights Scenario/01.Sub Level Access/TC 23756 Validate Multi CHild Level Display</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58b7f086-bfeb-4042-a7bd-ca5fad5f9cc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6966afd0-0a7f-473e-a725-e6304ff06ce0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2021caad-6d79-4a38-aace-ff815468685f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c640423-52fb-4ba7-b390-8344146092aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Rights Scenario/01.Sub Level Access/TC 23757 Validate Right for User Attach Right</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad738959-37e9-42b0-82f2-2d30e671650c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae882bcd-3523-4fef-a26b-3d11faaa8ffa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aca25b60-96fa-4367-81f0-45bc7068b10d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86102ffa-6eb5-4936-99e8-9af89deec8a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Rights Scenario/01.Sub Level Access/TC 23763 Validate SubChild Rights</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80795bbe-c5ac-4ef6-b39c-0f5f943d1a36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48e052ce-6277-4e99-8b1e-c8cadbbebd71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dccdcec8-2f46-4c51-8c59-4bf16b6f1ed0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4606464d-ef19-4d58-84ba-f7af9bf7110d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Rights Scenario/01.Sub Level Access/TC 23766 validate levels not displayed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20ad3159-77b8-48d5-950d-67d4ac9359e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cf76af5-07ea-42e7-84ed-efda50acd9ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16604f11-a5c9-4869-be4d-f561e14b151a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b865502b-cf9e-47ce-9360-d3895f517532</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca3652f5-023f-45bd-9e42-d3b0d1f21aec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2cdf5d3-a8ab-4488-83ad-ed9c5f925e15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Rights Scenario/01.Sub Level Access/TC 23767_72 validate levels with different access</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8eef6e60-1aeb-4c1f-b469-de7197c62d19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b54bfa8-7c33-4ba9-809c-46aead7ae805</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d49cae6c-eda1-4813-8f14-9d02a647ccaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a5b59d5-6af8-4b41-ac6f-d7c757a65fc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a36ef92a-73f9-4452-9f11-87936db67ec8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a6e1f54-c6d6-42b7-8a3e-ad7edae95cc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Rights Scenario/01.Sub Level Access/TC 23769 validate Access for groups attach rights</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18e37497-5e2f-4a08-9fee-983b4926df56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d72d766-f8fb-4465-8155-5c609987c9f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>510acb3c-57af-4474-9ec3-95c324116913</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>343026c4-0459-4f30-8c3e-0765406e505f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bfce3e9-c778-46d0-9371-016544a34e0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fd5275c-a8c7-44cd-8996-f090d84bc427</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Rights Scenario/01.Sub Level Access/TC 23770 Validate Only sub child in use</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c24b280f-8c1d-4955-93a2-a39df7bad3b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dd1ae7a-ea46-4946-a1f6-a9fa8620e68a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c81d8418-70ec-45df-9578-c9b19fa8cbf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5be696e-cda7-40bf-8a29-aef724dcf79b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8e3fef5-3506-4f57-b2dc-b07b71963129</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5868861e-6f0f-4461-a6d9-db2d79ac04ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Rights Scenario/01.Sub Level Access/TC 23773 Validate Parent and Child are Displaying</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>267e5fc6-1cd1-43d1-965a-f8c4b3034a88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c48143d-d4c0-4c7e-9388-db8bdcab440e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88aad41b-feeb-4c41-8ac9-07325d8cb8b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af18ede0-88ce-4de4-8bad-ab46bf26b19f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af1c5e82-7b6d-4c32-8296-796509105f81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3815e990-8285-450d-899d-68a8cdc5046d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Rights Scenario/01.Sub Level Access/TC 23774 Validating Parent Level alone</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3db2b383-4a38-4912-be83-61093da68fb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bd69a1b-e1a5-44f1-8b3b-0ae547aef13a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99a10f3a-253a-4979-9783-12f4282cfec8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c36de8b-3b21-4e00-91e9-91b9df5ee251</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>844b6687-df8e-4880-aa55-54f442fc565c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
