<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveInAssignAuthor_Button</name>
   <tag></tag>
   <elementGuidId>e4a28462-63ae-43b7-81f0-772714b31f6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@class,'btn-success')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@class,'btn-success')]</value>
      <webElementGuid>e43127c5-23ad-4af2-822d-07932884a97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DocPro_Module/iframeActions_IFrame</value>
      <webElementGuid>4e3f9d03-f755-4ff8-9b95-e4691e859642</webElementGuid>
   </webElementProperties>
</WebElementEntity>
