<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchInAssignRoute_TextBox</name>
   <tag></tag>
   <elementGuidId>ef8d78a3-8eb9-43b2-8151-2c37c47b6223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@aria-controls='assignRouteGrid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@aria-controls='assignRouteGrid']</value>
      <webElementGuid>fb634bd7-af40-425b-8985-e86897175bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DocPro_Module/iframeActions_IFrame</value>
      <webElementGuid>42ae1c1e-85b0-4cdf-acce-ec5018e4f3ae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
