<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchInAssignAuthor_TextBox</name>
   <tag></tag>
   <elementGuidId>ee9e4c5f-3da1-436e-8085-91d1e58680fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@aria-controls='assignAuthorGrid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@aria-controls='assignAuthorGrid']</value>
      <webElementGuid>d3b3cdc5-4b07-496b-aa6f-e8b43f261411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DocPro_Module/iframeActions_IFrame</value>
      <webElementGuid>0a86d703-a76d-447e-82c9-e81420e50464</webElementGuid>
   </webElementProperties>
</WebElementEntity>
