<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chooseFile_Button</name>
   <tag></tag>
   <elementGuidId>44f07f28-aab9-4c25-b33a-bc9edeccda42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='LocalImg']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LocalImg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LocalImg</value>
      <webElementGuid>6fc7c20d-d12e-4f37-a45f-42ea679cc3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='LocalImg']</value>
      <webElementGuid>4040a5ce-3bee-4841-80e2-62770308597c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Suite_Module/OrganizationProfile_Page/album_IFrame</value>
      <webElementGuid>3073c9d1-9fca-4235-af47-818476ffdb59</webElementGuid>
   </webElementProperties>
</WebElementEntity>
