<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchInReqNeedApproval_TextBox</name>
   <tag></tag>
   <elementGuidId>18b252af-9db0-47af-9b40-4431e855a47a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@aria-controls='requestNeedingApprovalGrid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@aria-controls='requestNeedingApprovalGrid']</value>
      <webElementGuid>c88bb244-ad15-476c-9ebf-a01a9c26166a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DocPro_Module/iframeActions_IFrame</value>
      <webElementGuid>78981b8a-98fc-4cb5-abc9-cd5bdf080ea7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
