<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchInDocNeedingRevision_TextBox</name>
   <tag></tag>
   <elementGuidId>011b3dc2-27fe-42d0-976d-6ec1ff1159eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@aria-controls='documentNeedingRevisionGrid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@aria-controls='documentNeedingRevisionGrid']</value>
      <webElementGuid>a136f355-6a37-435b-8422-e0af61f8775f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DocPro_Module/iframeActions_IFrame</value>
      <webElementGuid>bf268f7e-79ea-4379-bc17-8b305eefefd8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
