<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Site_PDF_Preference</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>41c24905-44e7-4dbd-9d17-1d799d80c72a</testSuiteGuid>
   <testCaseLink>
      <guid>67be5e07-c3f5-4326-9ce1-c2fd9bc6bc61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/SitePDFPreference/TC-23013,14 Validate Template Functionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5fee15c-acc5-4b0f-a4c8-43037ffee933</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66c2c845-acc2-4aed-a44a-8728b5dc17ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1ac9e09-a200-4c32-98b5-9f03a058fb01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df35e096-5311-4524-ad86-42c8ca8379ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/SitePDFPreference/TC-23015,16 Validate the enable enhanced printing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4db357ae-d747-4199-9425-7042af40ddf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fe319f0-a80d-4d1d-8def-dc4fcba37423</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec2e2ad5-8869-47a3-8b94-1b192cbf98c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>709a4ef8-a703-454f-86e2-301e9a34aacf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/SitePDFPreference/TC-23017,18 Validate Restricted View Checkbox</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9089da47-7644-4c9f-943f-d5744783b2d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4569bcc7-1bb4-49fa-b1d7-f0bceb331742</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a37f6a56-6d08-46ae-a05d-e31552fba2ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e84fc1e0-9519-4c05-b6a6-b71a3ac89a71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/SitePDFPreference/TC-23020 Validate Incude Template checkbox</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23cf4a8f-01d2-434b-a7e2-1e39a902770e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae689cce-3a78-4707-9c50-a71476694e8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a30915ce-c163-4639-9bc1-eeb805b16066</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6898fdf4-f44d-489f-b2af-23e5a3f21335</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/SitePDFPreference/TC-23024 Validate the search column</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c809bb89-315b-4214-be5e-c4f5a1db5770</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34aad69d-9da8-40af-a175-fd5252d8249b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12ddb39a-017b-43e6-b34c-294b8e07c9cf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
