<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_Button</name>
   <tag></tag>
   <elementGuidId>92e3dd6a-1a45-49fb-9542-712092333551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),'Add')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_add_hold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Suite_Module/Department_Module/Iframe</value>
      <webElementGuid>62ec892f-2f65-4a37-b523-715538acfda8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
