<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete_button</name>
   <tag></tag>
   <elementGuidId>7116505b-022f-4248-8594-8259e8a1fb1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@title='Delete']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Delete' and @ref_element = 'Object Repository/Department_Module/Iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bdelete_Grid_Dept_390</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>2b4bf278-b724-4984-9b34-ce48d3e37d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Suite_Module/Department_Module/Iframe</value>
      <webElementGuid>15e312b3-fae8-4076-b592-e7113bbff1f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='bdelete_Grid_Dept_390']</value>
      <webElementGuid>fcc22c85-b336-4333-87bc-18631a750297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Grid_Dept']/tbody/tr/td[2]/span[2]</value>
      <webElementGuid>a0b0940c-d18e-4452-a671-f95926e1509a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Production Department'])[2]/following::span[2]</value>
      <webElementGuid>1a920e1f-4792-40a4-966b-b1bd6bd3caaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::span[2]</value>
      <webElementGuid>c6bde9d1-3592-4965-b7fd-01b53321d6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[1]/preceding::span[1]</value>
      <webElementGuid>570bcd19-603e-4ed1-8c3e-c00e6a7f8209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View 1 - 1 of 1'])[1]/preceding::span[1]</value>
      <webElementGuid>e1b6739c-b97d-4b35-8818-700652454c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>2974324e-1d02-4799-b098-da3c2d780cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'bdelete_Grid_Dept_390' and @alt = 'Delete' and @title = 'Delete']</value>
      <webElementGuid>4c9d5548-3897-453c-bb9c-d0ac34382fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
