<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_button</name>
   <tag></tag>
   <elementGuidId>291d9093-5687-46b6-9a56-7efe075fdce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='clsbtnedit' and @title='Edit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bedit_Grid_Dept_390</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>77c423fa-8416-4555-a41c-2e4a067cd6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bedit_Grid_Dept_390</value>
      <webElementGuid>cad9dad4-5873-4233-a0e0-a4fcb5a8c378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>55e6abe2-e562-40ec-830b-c43e02550e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clsbtnedit</value>
      <webElementGuid>ae0ca2aa-d1a9-4b4b-94d1-ddb8310c3c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>597b5a0d-3768-4dd4-a6be-48192827b125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>InlineEditRow('Grid_Dept','390');</value>
      <webElementGuid>efd5b164-f4eb-4135-b1e9-9a8a54b1a4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bedit_Grid_Dept_390&quot;)</value>
      <webElementGuid>e8fdb875-6e58-4d4d-a3fe-1f0b71d887e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Suite_Module/Department_Module/Iframe</value>
      <webElementGuid>a03da0f6-dbf9-4eed-a624-814ff664ecb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='bedit_Grid_Dept_390']</value>
      <webElementGuid>48579331-bdbf-4f1f-9ef6-fd089422799b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Grid_Dept']/tbody/tr/td[2]/span</value>
      <webElementGuid>e3eb2d5b-3d31-433a-8419-b381394594be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Production Department'])[2]/following::span[1]</value>
      <webElementGuid>69837540-66d3-4f83-a35c-e809df7d2513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::span[1]</value>
      <webElementGuid>acf615d2-c610-4592-942e-77826fb00488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation'])[1]/preceding::span[2]</value>
      <webElementGuid>cb5b099e-1013-49e7-bae3-ad0d4e346a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View 1 - 1 of 1'])[1]/preceding::span[2]</value>
      <webElementGuid>5136564f-61fe-47fa-ac66-f05ec1de71ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>cdcbc6fa-f31b-4b2a-8fbc-1384aa11e41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'bedit_Grid_Dept_390' and @alt = 'Edit' and @title = 'Edit']</value>
      <webElementGuid>63a1092a-c4de-4abb-bd7e-5aa1b8a125b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
