<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>allOptionsScrollBar</name>
   <tag></tag>
   <elementGuidId>4b5a0d4b-4abd-44a7-b52a-509e8df7781d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside/div/div[@class='scroll-sidebar']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>scroll-sidebar</value>
   </webElementProperties>
</WebElementEntity>
