<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detailView_iFrame</name>
   <tag></tag>
   <elementGuidId>010deb53-1f10-40df-89b5-69bf6d16e4e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='Detailview']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Detailview</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Detailview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7fdef5c3-ec34-494c-8713-d73070155dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Detailview</value>
      <webElementGuid>26d7e591-d259-4e24-99ff-9580ce403c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Detailview</value>
      <webElementGuid>03cb978f-3e60-4f41-8fe4-d917ed522595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>hideModuleList()</value>
      <webElementGuid>e5e4e4d3-b402-4677-9810-cbbe388702cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onFrameLoad(this)</value>
      <webElementGuid>6de559b7-15ef-4d13-afe9-31129e5fb63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-wrapper</value>
      <webElementGuid>756e9a37-854e-4619-9d38-e6d32c83da72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Detailview&quot;)</value>
      <webElementGuid>b0d13695-0aab-43eb-8491-7a1e71733037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='Detailview']</value>
      <webElementGuid>fcec9dda-6300-4b37-b319-2d139dc71fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/main/iframe</value>
      <webElementGuid>5f04a0c0-115f-47c3-8845-4d2290deca54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2756c2b3-00c3-4868-8b06-53619d9f20bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
