<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>usersParent_OptionIcon</name>
   <tag></tag>
   <elementGuidId>81b08520-cd75-489d-920e-f68da8fa503b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='submenu']/li/a/span[text()='Users']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.collapse.show > li > a.has-arrow > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1375191a-5533-4a97-ad20-7ed8407380c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users기</value>
      <webElementGuid>c691ca04-3d5c-4cd5-890f-82d776d41c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarnav&quot;)/li[@class=&quot;active&quot;]/ul[@class=&quot;collapse show&quot;]/li[1]/a[@class=&quot;has-arrow&quot;]/span[1]</value>
      <webElementGuid>a43bab34-2600-4ea4-b45a-b8d17de19d0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebarnav']/li/ul/li/a/span</value>
      <webElementGuid>6cd09176-eba2-4cde-8b40-0cee31d06dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setup기'])[1]/following::span[1]</value>
      <webElementGuid>7c2a81a5-65dc-49a0-8a2c-b7d38f52bb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integrated Management System /QHSE Platform'])[2]/following::span[2]</value>
      <webElementGuid>9cf89cdb-e2b8-4b7f-9c2b-aa9446626eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users기'])[2]/preceding::span[1]</value>
      <webElementGuid>7cb9c9e3-241e-42d7-a211-fe2afb7feed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Rights Profile기'])[1]/preceding::span[2]</value>
      <webElementGuid>fc51643a-56fe-4f1c-9021-3b7d91e1ba06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Users기']/parent::*</value>
      <webElementGuid>e9259051-fca7-4ad8-82bc-50e48ff10c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a/span</value>
      <webElementGuid>dd5553c9-6a0b-46d7-85a8-482b0b9e34d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
