<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>usersChild_OptionIcon</name>
   <tag></tag>
   <elementGuidId>9765b6c4-b014-4578-8ca3-58bd66879cc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[@title='Users'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.collapse.show > li > a.has-arrow > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b12d1007-26a7-46ee-98b3-f8e8fd16c984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users기</value>
      <webElementGuid>48287406-aa1d-45c5-9e3a-cce20319c6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarnav&quot;)/li[@class=&quot;active&quot;]/ul[@class=&quot;collapse show&quot;]/li[1]/a[@class=&quot;has-arrow&quot;]/span[1]</value>
      <webElementGuid>73384885-bc64-4cfd-a497-461a77410874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebarnav']/li/ul/li/a/span</value>
      <webElementGuid>a5e0b417-12fc-4774-933a-f1a1d1636254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setup기'])[1]/following::span[1]</value>
      <webElementGuid>88567180-1b93-4142-bdf5-dd1b49e3a4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integrated Management System /QHSE Platform'])[2]/following::span[2]</value>
      <webElementGuid>7c6dc9f4-f95b-4da8-873e-850707c0089d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users기'])[2]/preceding::span[1]</value>
      <webElementGuid>7bbfab97-4ef0-4fd6-9014-7d2d2c864739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Rights Profile기'])[1]/preceding::span[2]</value>
      <webElementGuid>a16b5c7c-68bb-4d83-8b84-210c66059a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Users기']/parent::*</value>
      <webElementGuid>eb39d2d5-e0d5-462c-a44e-97e916de36e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a/span</value>
      <webElementGuid>39e68633-bbf1-4f28-ab84-917f67fa98be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
