<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Logout_Detailview</name>
   <tag></tag>
   <elementGuidId>4cbb23c1-b0db-4b73-8ab5-3e49c50444ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='Detailview']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Detailview</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1f890fac-82b0-4a6f-9639-833fc1bb7449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Detailview</value>
      <webElementGuid>242705cb-efc1-4ea3-be45-dc842bcd7cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Detailview</value>
      <webElementGuid>6c387b1b-d261-4ffe-abbd-4ebd9b6d08bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>hideModuleList()</value>
      <webElementGuid>1e9d15ea-38c1-4858-86f9-2e7786e616ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onFrameLoad(this)</value>
      <webElementGuid>b8593a3d-e4d8-4c5f-a548-fc4f32e80051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-wrapper</value>
      <webElementGuid>2b4d5caf-023c-4cce-8bd1-969a384a647d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Detailview&quot;)</value>
      <webElementGuid>a77babaa-207b-4efe-82c7-7ca9fbc6d1cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='Detailview']</value>
      <webElementGuid>1e052ea0-e4b8-4d89-97f0-2e6f2c387e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/main/iframe</value>
      <webElementGuid>70838953-bb74-435f-8943-b10e024f7519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6363ad17-9ae1-42df-99a8-187e7d85ab8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'Detailview' and @id = 'Detailview']</value>
      <webElementGuid>4f9bd9a7-e712-436f-b513-89f68b99c151</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
