<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Logout_Detailview</name>
   <tag></tag>
   <elementGuidId>ebc0d989-621c-408f-9421-a0ef8df09f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Detailview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='Detailview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8e8963f4-19ce-486f-b889-dc369fd43bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Detailview</value>
      <webElementGuid>14dd44ac-6b60-4f6f-b3c3-04a47313827a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Detailview</value>
      <webElementGuid>b1a1d85c-ac9e-4915-b65e-365a4889f3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>hideModuleList()</value>
      <webElementGuid>98ee099b-ad47-46ca-b8a0-06677fa07758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onFrameLoad(this)</value>
      <webElementGuid>922f8495-fda0-466f-bf94-7dd394eaa6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-wrapper</value>
      <webElementGuid>37f7bb5b-c026-4be5-8bf8-0b5a7159ec7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Detailview&quot;)</value>
      <webElementGuid>a3ba50a2-38c7-4034-84fc-0d25355ed003</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='Detailview']</value>
      <webElementGuid>7a6192c8-224b-4e1c-855d-b7bf18699be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/main/iframe</value>
      <webElementGuid>319e7ba3-2ced-42e3-835e-bb2f213debf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4e474eae-00b2-429b-877f-a1b80a6954df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'Detailview' and @id = 'Detailview']</value>
      <webElementGuid>cc370646-2f70-43af-ae0b-aadc0f14e43f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
