<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_QA-Project-01_iframeActions_top</name>
   <tag></tag>
   <elementGuidId>46bc38c0-12b9-4180-95c8-6ca9daedf119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframeTree</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeTree']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7fd7439d-585e-4ea1-86df-ecc0171e9ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeTree</value>
      <webElementGuid>de8a899e-63d7-43db-8243-e9241feb7aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframeActions_top</value>
      <webElementGuid>15e96641-333d-447f-9f23-610734ccc444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d2835b28-0750-4a4b-9366-52825c0bb0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>hidelaodingsymbol()</value>
      <webElementGuid>7a134882-7bab-4979-ad19-6e8d6014c9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cloudqa4.ewqims.com///Common/DocPro/levelformsuite/levelformsuiteView?isNew=1&amp;suite=0&amp;righttype=2&amp;sitelevelname=Root Level&amp;parentlevelid=0&amp;levelid=#</value>
      <webElementGuid>00fcc24b-57f0-4d9e-a7fe-21fa1b77cb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeTree&quot;)</value>
      <webElementGuid>80133978-d31d-4660-8fef-ee256dbdc24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_EwQIMS/iframe_Logout_Detailview</value>
      <webElementGuid>6ad29c25-6a1c-4429-b5d0-ad18a24e8f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeTree']</value>
      <webElementGuid>8d3a7bee-2134-44bc-905b-d001f2fb8d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentPanel']/div/iframe</value>
      <webElementGuid>75a0cff2-61fc-441f-a5de-f8ed27f58ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0b45c6d0-40e7-4fa5-8c5a-8b7923df9ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeTree' and @name = 'iframeActions_top' and @src = 'https://cloudqa4.ewqims.com///Common/DocPro/levelformsuite/levelformsuiteView?isNew=1&amp;suite=0&amp;righttype=2&amp;sitelevelname=Root Level&amp;parentlevelid=0&amp;levelid=#']</value>
      <webElementGuid>670c7766-e6c5-4bb5-b4e3-89e87b9204dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
