<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Allow Site Sub-levels Creation</name>
   <tag></tag>
   <elementGuidId>b14510ba-21e9-4364-8815-f54a500fa9f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thAllowSiteSub</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='thAllowSiteSub']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fc03539f-fa07-4676-a5ed-b67122103636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thAllowSiteSub</value>
      <webElementGuid>f30ab19c-241b-465b-aff1-27a9bf9c1a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chkAllowSiteSub</value>
      <webElementGuid>30582aae-e80f-4ffd-b993-d3325980f8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label</value>
      <webElementGuid>b3a79fb2-9dd4-46cb-8822-36f9363f698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allow Site Sub-levels Creation?</value>
      <webElementGuid>a1478e33-21b1-4935-ae32-cb84b1707015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thAllowSiteSub&quot;)</value>
      <webElementGuid>e75313bb-356a-46ae-8f5e-84aea4c730e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_EwQIMS/iframe_QA-Project-01_iframeActions_top</value>
      <webElementGuid>b7cff517-a104-41b6-9b34-fe63b6853779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='thAllowSiteSub']</value>
      <webElementGuid>b971030d-8fde-427e-9aa9-62db09ad8fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmlevelformsite']/div/div[4]/div[2]/div/div/label</value>
      <webElementGuid>b69d3c63-1931-4fb9-9a28-9edc284e0a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow Site Modification'])[1]/following::label[1]</value>
      <webElementGuid>8e2c2c48-79fc-4784-8f1f-901ae6fcd655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[4]/following::label[2]</value>
      <webElementGuid>b972b401-3f86-41b0-ad40-900fca3d4f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::label[1]</value>
      <webElementGuid>d80cf255-131f-46e8-a8cf-9a9db470fded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::label[1]</value>
      <webElementGuid>7b912137-2158-4627-a1da-dc6bf03d8646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Allow Site Sub-levels Creation?']/parent::*</value>
      <webElementGuid>f0582532-58bb-484b-91b2-751da8f5fe80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/label</value>
      <webElementGuid>135adb13-45cb-4223-9378-89c9fbad136b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'thAllowSiteSub' and (text() = 'Allow Site Sub-levels Creation?' or . = 'Allow Site Sub-levels Creation?')]</value>
      <webElementGuid>79a5f092-ed79-49fc-9e8b-cd720d85e4b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
