<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Scope_06022023140118_bdelete_Grid_EditProcessScopeGrid_44</name>
   <tag></tag>
   <elementGuidId>215cea71-8cc0-4b3d-8d51-c218ea9af567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='bdelete_Grid_EditProcessScopeGrid_44']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bdelete_Grid_EditProcessScopeGrid_44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>75b78b1e-c270-4268-bdd0-e2ebb5fc6a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bdelete_Grid_EditProcessScopeGrid_44</value>
      <webElementGuid>3e343625-1bfb-468c-a96f-6a0f4b9cc8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>95aa57be-d5c9-430a-97fa-1905135651bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>984297b2-e1f2-43ec-8ac7-3688ac9ef78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>InlineDeleteRow('Grid_EditProcessScopeGrid','44');</value>
      <webElementGuid>9c2ea1fb-c6ad-40d3-9c5a-a91b270709f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bdelete_Grid_EditProcessScopeGrid_44&quot;)</value>
      <webElementGuid>f9e2a46f-ccbe-4989-94de-3a231f807505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_EwQIMS/iframe_Logout_Detailview</value>
      <webElementGuid>a4ba8685-4ab5-4a9c-81dd-c56e3b71f597</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='bdelete_Grid_EditProcessScopeGrid_44']</value>
      <webElementGuid>475c02c9-746d-45b6-a922-95487c9a287a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Grid_EditProcessScopeGrid']/tbody/tr[3]/td[2]/span[2]</value>
      <webElementGuid>ca87cfb1-1038-4471-84d2-a8f2a46348c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scope_06022023140118'])[1]/following::span[2]</value>
      <webElementGuid>b7767fb7-11a2-46ae-accc-c07c9bf030e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Auto'])[1]/following::span[4]</value>
      <webElementGuid>680a2789-3a63-4541-89c7-6ebf9805d9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scope_06022023141054'])[1]/preceding::span[1]</value>
      <webElementGuid>732e054a-c196-4cc7-8dd7-f58fc4e5f61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View 1 - 3 of 3'])[1]/preceding::span[1]</value>
      <webElementGuid>338bf375-29e3-4716-94eb-8f648c42c332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/span[2]</value>
      <webElementGuid>1efb01e2-a5ee-4e6c-9469-24b38b8a6120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'bdelete_Grid_EditProcessScopeGrid_44' and @alt = 'Delete' and @title = 'Delete']</value>
      <webElementGuid>6daa8e01-97d8-4dea-8a27-35dd62859c9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
