<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Suite_Module</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a6213d2b-b09c-443f-9a99-e6e286838cc8</testSuiteGuid>
   <testCaseLink>
      <guid>4da2b6b8-74c1-429b-9542-065ddac18a43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Create Country, State, and City functionalities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>136f9155-3fc5-4086-b495-e3036a6e81e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>165af512-bb5f-4cfd-8bee-302238f00bd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef4efeb2-2628-43b4-bb88-e8972dc7f858</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10b59a35-f237-47b1-9490-052853c7a6a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Create entity, assign owner and delete entity</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8eda28ea-a148-4c66-9d7b-8c58d8e1eac3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c93191df-ee6a-456f-9c39-089dcaa366c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b49be9b-1a20-4927-910b-03a7f8bf803b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Create, Modify and delete tags</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8955ed92-7f26-4a95-ace9-4de9ef7c2751</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7f477cc-1899-4382-8d4c-952116df359d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Update data and validate in Admin settings</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03dd4aa9-4b55-4e54-ae38-4ef9103c09f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1a32a4c-f705-4d7a-a190-de402ca8d8b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1469ae5d-c821-4f2a-9004-5b3496e1ce73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee8d97c3-17c1-4916-9fe0-efcf839ce65a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f570cd2-1c3f-4575-a713-a8abcc9b6702</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1c013ee-b9e5-4bde-90fc-0156f268ff00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b04460ce-8da7-41e2-a327-d1158fb66576</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Update data and Validate in Organization profile</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>85e8915a-c088-45ff-bf3a-a534fbe5383d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the City Creation and Deletion functionalities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef2e59a8-56ab-413b-a0d0-17a2c8c93276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cea75146-0c73-4961-82bf-b571730c9399</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fb642be-b465-493f-8098-74c2536576f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e5ffa1a-ea53-4124-95f7-ca5c87a85395</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the Country Creation and Deletion functionalities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fca758d-05d4-4349-87e7-eae018f627e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97ad51a6-6231-4fd6-a977-a7a9d3bbc332</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the Forgot password functionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>892464ad-1751-4bf9-a33a-bed9c1b64d94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b44b1102-0c3a-4fce-b453-a2a7078b8050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>558bb9bd-a186-4b84-bef7-deb78f6911c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fad37344-22ea-4a6a-8337-3228e4a40fa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3411c9e-a739-4882-beac-9616df2a6175</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6834ec8-3729-4b87-8bdd-c3fc2fb89395</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>964efd7f-fe24-45d2-bb1f-ba2f0f7afdf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56c65b05-9cda-4cfb-b483-3de4bccc5468</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>266f415c-eea5-44c6-9521-5a99afa00593</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ecfa13d-39ec-4384-ab86-a5bcbc23467e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the Position Creation and Deletion functionalities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9b5591f-94c5-4d91-a933-961e56224d7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7349f16a-2c76-48e8-b486-ae2df712c4b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5ffbcb5-db37-4dd9-9d3e-2fa4af241b35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the Remember me functionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>827d5515-efc6-43ac-9ffa-46984fa70343</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the Shift Creation and Deletion functionalities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c35837a-b262-4598-a263-94ca48d7dba0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aeb86f4e-15d3-4827-b22d-2a8c7790cc5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44ef7c49-8023-4f0c-90f3-5005c20e33a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac5ef9d6-b981-43cb-9bfc-58c4540f937b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f17b3ab6-b88c-406c-94ef-aac56ab518db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b87dfdf-75bf-46e8-a597-35cdde6624c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the State Creation and Deletion functionalities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>165af512-bb5f-4cfd-8bee-302238f00bd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e253ffde-a5ba-4f26-80b0-2b852428eaf5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47b160a8-403d-4fde-9d6a-3f4662976714</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the unlock user functionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>020f494d-9f29-4a86-8d69-62e78e6f9d7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81f6ef4e-ef55-44a5-bece-e23d0b3f3062</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the User is able to Add and Remove Users for module</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b551e0-00f7-47e7-b2de-0589588fb548</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1210c0bd-e4a1-4626-8781-23a1831b7531</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c015eec-d78f-4678-8a4a-d134578bd9a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>483f777e-4612-47aa-9dd5-b9dab705f257</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>831c3dd5-1af7-4bbb-9e3f-79bee3945ae0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9a509d6-97ec-4841-9e1f-2938d5160112</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the User is able to create, delete meetings</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>357e24f6-7d72-44cf-8d3a-41975777ed13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9e3116-96a0-4b42-98a4-b1f770ed90d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5080cf96-a9ff-4a2b-ba61-05b0cca5066c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6080d049-31e8-43a9-8d65-31d3ddddae6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53bf5eb9-6b70-4b84-a7d1-ce729a7e2e64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a1e56a0-720b-4851-a8a7-aad3b1c8a63b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43a0e073-e8c2-4430-a7ab-c5a2326520c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the User is able to create, delete Team</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>694dbceb-e26e-4f58-8bc5-fa75edf7ac5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96722a81-81dd-47d1-a47d-88b5531ce21c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2884147-09e7-4147-9c2d-2bb09f83dffc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the User is able to create,delete Customer</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c863027b-f7b2-464c-90ff-6c73afda764f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ca7a8eb-80b4-4f46-90be-f9e4763c5c60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2937c8b4-4d28-46fa-beb8-fab31335867d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46f82282-6d06-4dad-8b36-573bfcdc6209</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29b564d1-3eb1-4d7c-a425-7c6efc9116cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b912249-88bf-4123-9455-2a8b99dfe4bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the User is able to create,delete manufacturer</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e3969db-0aae-47aa-be9d-cd62b8cdb23f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f95d3bb-f351-47dd-a5b2-5514cc801ae6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3400ccdf-b0fe-4f92-b5f2-81a74a59ec35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the User is able to create,delete Supplier</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48897d1b-eeab-4901-882d-76234a1e2a35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a08e0350-6b46-478e-992e-ae41da7aabd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da8ad318-e781-4894-bd92-d6e529be7efa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0af8b8a6-e618-493c-a560-7ec2c6783d79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the User is able to create,delete Vendor</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5093ebc4-7c7b-47cd-bf61-42adeb879359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8da10241-2da5-4ca5-a741-47ffb91ede37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>645e17ae-4854-4b39-8bc7-d44d68e79efd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the User is able to create,Modify,delete groups and add and remove users</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e23ecf18-43ec-4dac-b801-659ff4b03b61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9de3d9c2-d205-495a-ba20-83b50c0d23d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>483ea542-3dbe-45ca-a59e-a66ddd451815</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify the User preferences functionalities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a61ea5ec-75ef-4fcd-89fe-c9bc2204bb2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f9744ce-d066-4e2b-8767-06075225df99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71560e05-ae45-4784-9971-e8314c80b456</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6966efb-b89d-4405-8c8d-6c8c9054d6df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>892464ad-1751-4bf9-a33a-bed9c1b64d94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b44b1102-0c3a-4fce-b453-a2a7078b8050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>558bb9bd-a186-4b84-bef7-deb78f6911c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fad37344-22ea-4a6a-8337-3228e4a40fa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3411c9e-a739-4882-beac-9616df2a6175</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6834ec8-3729-4b87-8bdd-c3fc2fb89395</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>964efd7f-fe24-45d2-bb1f-ba2f0f7afdf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56c65b05-9cda-4cfb-b483-3de4bccc5468</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>266f415c-eea5-44c6-9521-5a99afa00593</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45011d1f-2d02-4f49-a1dc-66a3c08a76fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify whether the user is able to change password from preferences</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>892464ad-1751-4bf9-a33a-bed9c1b64d94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b44b1102-0c3a-4fce-b453-a2a7078b8050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>558bb9bd-a186-4b84-bef7-deb78f6911c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fad37344-22ea-4a6a-8337-3228e4a40fa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3411c9e-a739-4882-beac-9616df2a6175</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6834ec8-3729-4b87-8bdd-c3fc2fb89395</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>964efd7f-fe24-45d2-bb1f-ba2f0f7afdf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56c65b05-9cda-4cfb-b483-3de4bccc5468</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>266f415c-eea5-44c6-9521-5a99afa00593</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8dc4595f-5a8f-4cc5-a09c-434ea83c4d5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suite Module Test Cases/Verify whether the user is able to create, search and delete user</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>892464ad-1751-4bf9-a33a-bed9c1b64d94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b44b1102-0c3a-4fce-b453-a2a7078b8050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>558bb9bd-a186-4b84-bef7-deb78f6911c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fad37344-22ea-4a6a-8337-3228e4a40fa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3411c9e-a739-4882-beac-9616df2a6175</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6834ec8-3729-4b87-8bdd-c3fc2fb89395</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>964efd7f-fe24-45d2-bb1f-ba2f0f7afdf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56c65b05-9cda-4cfb-b483-3de4bccc5468</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>266f415c-eea5-44c6-9521-5a99afa00593</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
