<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_yes</name>
   <tag></tag>
   <elementGuidId>93dc92a4-f49c-4794-93dd-d3e3f63b370b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tmp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tmp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73a7fb0b-461f-43fe-a1d6-f3a4b1fdc63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tmp</value>
      <webElementGuid>3e6321e5-9b96-4e11-80d1-1bbee5781067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>df01dbe7-bd96-48d3-a2f3-573025c8faaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tmp&quot;)</value>
      <webElementGuid>9c7e84da-932e-48b3-bffb-9681c06132b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Hakeem/Page_EwQIMS/iframe_Logout_Detailview</value>
      <webElementGuid>4b9dd7ca-14ea-45d6-84f8-13c7ad5b9230</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tmp']</value>
      <webElementGuid>21398811-4470-4d8d-95cd-520b98787c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='embody']/table/tbody/tr[2]/td[2]/div</value>
      <webElementGuid>d04a2a36-9c72-4efa-b8cc-e0abcde46aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Default Format'])[1]/following::div[1]</value>
      <webElementGuid>f37ebbed-1cef-41aa-b1ee-71e14f0c8811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[1]/following::div[2]</value>
      <webElementGuid>3addcff6-eca6-4b62-a7ca-52aaf50568b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::div[1]</value>
      <webElementGuid>9554623c-9546-443b-9864-f723dbbe2f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[1]</value>
      <webElementGuid>55bb00c7-9ddb-4e00-af40-a43c43735b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='yes']/parent::*</value>
      <webElementGuid>5fb82428-e390-44a3-b5a8-37023c60b033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div</value>
      <webElementGuid>0ab32647-b19c-4e46-9f07-378d1fc25820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tmp' and (text() = 'yes' or . = 'yes')]</value>
      <webElementGuid>1bc30b99-e521-4a1d-804e-0cdd25672334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
