<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Logout_Detailview</name>
   <tag></tag>
   <elementGuidId>025c322b-e7b2-4b7f-9283-8f7d95ef475d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Detailview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='Detailview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e711576b-7192-426f-a94f-dc10b949b700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Detailview</value>
      <webElementGuid>21a40a84-e238-4063-b14e-7e95d416ca31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Detailview</value>
      <webElementGuid>dbcfec49-66b6-40b1-b6d8-9ceb8a89775c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>hideModuleList()</value>
      <webElementGuid>38a4e634-5416-4949-bdbf-605bc0b974cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onFrameLoad(this)</value>
      <webElementGuid>576cbd9f-40ec-4fe4-a4a0-2c1719d4caf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-wrapper</value>
      <webElementGuid>5000fa51-59ae-4761-87bb-4b4180ed8175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Detailview&quot;)</value>
      <webElementGuid>135ec078-7e0f-4adc-b07e-de7b844ab2d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='Detailview']</value>
      <webElementGuid>73cae586-4c00-4d2f-99cf-6344601f020a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/main/iframe</value>
      <webElementGuid>79bab77a-ee18-4f72-9a22-a2b0d5b3197c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>57cdcf21-389f-41e0-9ad6-d813bbe9461f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'Detailview' and @id = 'Detailview']</value>
      <webElementGuid>16d59d77-0d55-4902-adac-3d69b72d1fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
