<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Global (Manufactured Production Item)_imgFormats</name>
   <tag></tag>
   <elementGuidId>4763c17a-4d26-4382-9993-54974fd3d810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgFormats</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgFormats']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5491bfb6-6425-481c-8def-733c5de317e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgFormats</value>
      <webElementGuid>b18209ac-ec88-4c33-b57a-739df285813a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./Images/Format.png</value>
      <webElementGuid>4f64a4b3-7d95-43bf-b0f1-5006ce2f9d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Format settext</value>
      <webElementGuid>12e97703-e70a-488f-a85d-7f6d3729d9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>objsrcevent</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>16680658-ff48-4e44-ac82-a3b48e0ce226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lmImgNorm</value>
      <webElementGuid>f5b66f56-7104-4668-ba5c-002e1b5d391a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgFormats&quot;)</value>
      <webElementGuid>ba4f1d1d-380d-4460-ae82-aa3aaad603cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Hakeem/Page_EwQIMS/iframe_Logout_Detailview</value>
      <webElementGuid>9d375cb0-e425-432d-968e-167a794925de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgFormats']</value>
      <webElementGuid>02047d3f-8212-4389-b335-4a6e2e79b3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbitemsdiv']/img</value>
      <webElementGuid>0357f2aa-284a-4bd0-a0a3-5be2e14a4a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Format settext']</value>
      <webElementGuid>5497961c-3d3c-4838-a887-006730861177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>0309069f-5607-48e9-b83c-25de8bd7cf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgFormats' and @src = './Images/Format.png' and @title = 'Format settext']</value>
      <webElementGuid>cce4d237-eb0d-4d10-91f2-15e097ad33db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
