<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Name_et1 CLR_CELL_FOCUS</name>
   <tag></tag>
   <elementGuidId>e5096426-5ef1-4de0-bb07-d25f79b50ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.et1.CLR_CELL_FOCUS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='embody']/table/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a18a2bd1-e032-4d83-a3c5-4976e8615168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et1 CLR_CELL_FOCUS</value>
      <webElementGuid>f8125100-ebb5-4d6d-8b2e-933c44363bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;embody&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;et1 CLR_CELL_FOCUS&quot;]</value>
      <webElementGuid>be717702-bcaa-4e7d-b259-e4c252ea82a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Hakeem/Page_EwQIMS/iframe_Logout_Detailview</value>
      <webElementGuid>a4971129-6c28-4641-8113-db164588b0f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='embody']/table/tbody/tr/td[2]</value>
      <webElementGuid>79bca363-36f4-45e4-9f8b-da5dd99dfd2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::td[1]</value>
      <webElementGuid>d44abb0a-985a-46fe-866f-5c839a5c8cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Use Regular Expressions]'])[1]/following::td[2]</value>
      <webElementGuid>2ffedc79-f9eb-4e7d-91d6-bd76149a8469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Default Format'])[1]/preceding::td[1]</value>
      <webElementGuid>db4a87b5-6729-4009-b96e-4e5eacc42eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='yes'])[1]/preceding::td[2]</value>
      <webElementGuid>8519ceaa-1721-4259-aaec-400732ed4ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>d0bce337-4fd1-4363-8bf9-1d88e4c87962</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
