<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Global_etext</name>
   <tag></tag>
   <elementGuidId>af362eca-8824-4936-8cbf-062a33525c7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#etext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='etext']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5e4bf54c-10f5-46d6-92bf-2ee55be1c784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>etext</value>
      <webElementGuid>feeaa946-2d9c-4317-854c-6d7f3b970feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>73915047-40d9-4d81-bb5b-b92f7ce241a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ecb50c54-57cd-4126-8a66-d49cc4adc062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselectstart</name>
      <type>Main</type>
      <value>event.cancelBubble = true; return true;</value>
      <webElementGuid>5607960f-4914-4a47-8a44-3f1588849dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>EditBlur()</value>
      <webElementGuid>2fee8af4-e0e5-411c-89e2-174f4c613dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>EditFocus()</value>
      <webElementGuid>f161821d-f03d-4e56-a1f6-077847057163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>EditKeyDown()</value>
      <webElementGuid>345136ed-d84d-445a-b4d7-01ad2dd1b8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>EditKeyUp()</value>
      <webElementGuid>9c99d1a1-f378-47d7-83f6-5ebd6c0a0731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>EditMouseDown();</value>
      <webElementGuid>649119da-deb4-4727-badd-1cdbb7558c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;etext&quot;)</value>
      <webElementGuid>5c85180b-2781-40c5-8fd0-6a5030e2e01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Hakeem/Page_EwQIMS/iframe_Logout_Detailview</value>
      <webElementGuid>7b3b1bd4-d893-4848-ace4-b02dee3e203b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='etext']</value>
      <webElementGuid>0eb5f206-9d0a-4a86-8ab2-b87e7202a2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='mainbody']/textarea</value>
      <webElementGuid>9123100d-573d-478a-8a33-4c3ea6403b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>95a5c3f8-43a9-4305-a4ba-9d890dec7a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'etext']</value>
      <webElementGuid>deec8566-8487-4427-941e-862edb390dae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
