<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>EwQIMS_Levels_Create_Delete in use</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c26b26b6-2160-4356-9225-34fd02e553c8</testSuiteGuid>
   <testCaseLink>
      <guid>1e69181e-0bd3-49ee-8f1b-14e0e3797772</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Levels create and Delete/TC-21854 Validate user can view levels created by suite administrator</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1e93ff98-3f26-4c4b-8198-ed2cc56c2189</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Levels create and Delete/TC-21855 Validate user should not view levels created by suite administrator</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e636d430-afc9-4081-b8f9-f62d88cd5d90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Levels create and Delete/TC-21856 Validate the user can activate the levels for the specific site</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa2ca396-0ac5-4d67-9c7a-3479d291a819</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88203ee5-ef6d-4610-bb10-1db8be3eb045</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Levels create and Delete/TC-21858 validate Delete should be Disabled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>827a5f5a-9a7f-4ee2-b71e-fd7a20468767</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e20a20d2-8f88-4115-8c55-324b6fcd333e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Levels create and Delete/TC-21859 validate the user can Edit the level by suite administrator</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fbb0775-76d2-464a-a304-638f38b04ce5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ad28aaa-4439-47c1-9a23-715babb31f19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Levels create and Delete/TC-21860 validate New Option should be Disabled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5010b8c-8575-4351-b149-10b42c1f588a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>188bf239-932f-48d8-ad67-8782c57a6255</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Levels create and Delete/TC-21861 validate New Option and Sub level create, Edit and Delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>528fd614-d9e0-4626-a7f9-646919b14aec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01311a42-8fba-45b9-b833-6aac779f793c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6052eea6-a2c0-4e6d-aea5-a4879c877376</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bdec89c9-e7d5-4c02-85f4-cc7171233363</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DocPro Module/Folder Management/Levels create and Delete/TC-21870 Validate the module levels are not displayed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c70d9277-f642-4122-b305-2c3486b8c487</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
